lib/sql.php

Trying to set a value to `null` before resulted in a string value of `''` (empty string) instead of an actual null value.
The string `'null'` is not affected by this change and will still result in a string value of `'null'` in the DB.

Add null to list of SQL literals

---

lib/sql.php

In order to increase compatibility it is advisable to use backticks as quote sql identifiers. While sqlite usually runs fine with double quotes MySQL requires ANSI_QUOTES mode to be enabled. In the createTable method you correctly replace double quotes with backticks. 
In the remaining methods (insert, select, update, delete) table identifiers are not quoted at all. These would break if users use any reserved characters in table or column names (e.g. the space character). Don't know why someone would do that, but maybe it would be a good idea to support these use cases...
(Sorry for fixing these issues 'bit by bit', but I just discovered them while debugging my own application)

Use backticks for sql identifiers

---

lib/url.php

Make the `Url::build()` method build correct urls when a hash is involved.
See #88 for extended description.

Fix Url::build() method. Fix for #88.

---

lib/upload.php

iphone hack unexpectedly removes dot between filename and extenstion

iphone hack removes dot between filename and extenstion

---

lib/email.php

This class already has de ability to extract the email address from a string like 'Email Label <email@domain.com>' by using the `extractAddress($string)` method, but it never was used to extract the address in the `validate()` method.
This also was issued here: #95

Fix email validation with the format 'Name <email@domain.tdl>'

---

lib/database.php

Because of the syntax change, PHP 7 threw an "Array to string conversion" error. This change works for both PHP 5 and 7.

Fix PHP 7 compatibility

---

test/SystemTest.php

Checking for "bash" is not as reliable as it should be as some users/environments have another bash installed at /usr/bin/bash or /usr/local/bin/bash.

Fix SystemTest to work on more systems

---

lib/upload.php

See http://php.net/manual/en/features.file-upload.multiple.php.
To use this PHP feature with this class, the user can create multiple instances of `Upload` in a loop, each with an incremented `index` value.
Also see https://forum.getkirby.com/t/allow-guests-to-create-pages-from-panel-or-frontend/2854/8?u=lukasbestle for the background of this feature.

Accept PHP's syntax for multiple uploaded files

---

lib/url.php

[cloudflare](https://www.cloudflare.com/)’s proxy sends `https, http` as a `HTTP_X_FORWARDED_PROTO` value for ssl enabled sites. this will fix it for websites behind the service.

fix ssl setting with cloudflare

---

lib/s.php

Fixed the error that comes up if the visitor has no UA set, which occurs if PHP or Node.js tries to pull data.

Fixes Undefined Index: HTTP_USER_AGENT

---

lib/xml.php

Add `LIBXML_NOCDATA` to `simplexml_load_string` in `parse` to preserve data wrapped in `<![CDATA[]]>`.

Add LIBXML_NOCDATA

---

lib/database.php
lib/database/query.php
lib/sql.php
test/DbTest.php

To improve security and code readability, I have refactored the database classes `Database`, `Database\Query` and `Sql`. Some minor features have been added along the way. Full changelog:
- Quote identifiers (tables and columns) to allow using reserved names and strange characters in identifiers
- Validate table and column names using a whitelist
- Use bindings instead of quoting internally
- Bind all parameters that can be bound (everything except SQL string parameters)
- Validate SQL keywords, predicates and operators like `<=`, `IN` and `PRIMARY KEY`
- Split up SQL class into MySQL and SQLite specific methods where necessary to improve code readability
- `$query->having()`: Support for the `where()` syntax
- Use TIMESTAMP type for timestamps in MySQL instead of INT
- Disable prepare …

Refactor database classes

---

lib/dimensions.php

Replaces the ‘x’ with the typographically correct times symbol × (aka `&times;`).

Replace x with × in dimensions

---

lib/html.php

In my kirby patterns I like to keep my html classes organized within arrays, which makes it easier to filter undesired classes. It would be useful to allow users to pass such kind of arrays to the `attr()` helper function as it reduces the amount of required code:
Following an example:
Before:
```php
<nav <?php echo attr('class', implode(' ', ['navbar', 'navbar--justify'])); ?>>
</nav>
```
After:
```php
<nav <?php echo attr('class', ['navbar', 'navbar--justify']); ?>>
</nav>
```

Allow the `attr()` function to handle multiple values

---

lib/router.php

The `host` option can be used together with the pattern to limit a route to a specified host. Required for cross-domain multilang in the CMS.

`host` option for router

---

lib/escape.php

Follow up for closed  #191 
Kirby requires at least PHP 5.4, so there is no need to keep the legacy code in.

Removed PHP < 5.4 legacy code

---

lib/escape.php

Follow up for closed PR #180 
$strict should always be the default to cover cases where attributes might be unquoted or quoted illegally (e.g. backticks are valid quotes for IE)

Fixed wrong comparison

---

lib/header.php
phpunit.xml
test/HeaderTest.php

As a fix for https://github.com/getkirby/toolkit/issues/212, I tried my hand at making a few improvements to the `header` class.
Changes are:
0. Wrote a bunch of tests. Yay, tests!
1. Add 7 entries to `header::$codes`. Main ones are:
- `410 Gone` for deleted/archived content (more info: https://indieweb.org/deleted).
- `451 Unavailable For Legal Reasons`, a special case of 404/410, poetically named after Fahrenheit 451 ([RFC 7725](https://tools.ietf.org/html/rfc7725)); admittedly it’s still a Proposed Standard.
- `504 Gateway Time-out`, can be useful if you’re doing a server-side request on some API which times out.
2. Added a `header::gone()` shortcut for `410 Gone` statuses.
3. `header::status()` default for an unknown code is now a 500 error, and not a 400 error. No need to tell a …

Improvements to header class (header::status, mostly)

---

helpers.php
test/HelpersTest.php

I'm currently working on v3 of the [Uniform plugin](https://github.com/mzur/kirby-uniform). This version will be based on the [kirby-form](https://github.com/jevets/kirby-form) plugin which in turn makes use of the [invalid helper function](https://github.com/getkirby/toolkit/blob/fc3b1e886babbbc62b7a98f3deadbc639f1b9717/helpers.php#L312) to validate the form fields. To this end I'd like to propose some improvements to the invalid function. This PR consists of two idependent commits:
1. Improved 'required' validation. Now only `null`, `''`, `[]` or undefined variables are rejected by the required validation. Previously `'0'` was rejected, too.
2. Improved error messages. Now an array of error messages can be defined for each validation rule, too. Each item of the array corresponds to one …

Improved invalid helper function

---

lib/str.php
test/StrTest.php

I was expecting parse_str() to be a mode of str::parse(), but it was not. I think it’s a good addition, especially because parse_str() by default throws stuff in the global scope, so you need to pass in a variable by reference and all that stuff.
Also added tests!
From [php.net](http://php.net/manual/en/function.parse-str.php):
```php
$str = "first=value&arr[]=foo+bar&arr[]=baz";
// Recommended
parse_str($str, $output);
echo $output['first'];  // value
echo $output['arr'][0]; // foo bar
echo $output['arr'][1]; // baz
// DISCOURAGED
parse_str($str);
echo $first;  // value
echo $arr[0]; // foo bar
echo $arr[1]; // baz
```
And now:
```php
$a = str::parse($str, 'form');
```

add parse_str() to str::parse()

---

lib/a.php

Before the `$decimals` parameter simply had no effect at all.

Fix A::average for decimals of returned number

---

lib/folder.php

When you try to copy a folder inside itself you get a recurisve folder creation because the content of the folder is scanned after the creation of the destination folder.
https://github.com/lukaskleinschmidt/kirby-sortable/issues/38

Fixed recursive folder creation

---

lib/str.php

I saw an issue with my local PHP installation where using the `widont` function in a plugin would fail if the string contained the name `František Štorm`, which obviously has characters outside of the ASCII range.
Appending a `u` to the regex fixed it for me.
See also https://stackoverflow.com/a/31232938 and https://stackoverflow.com/a/1766767.

Make widont regex multibyte-safe (UTF-8).
